draft 13 and more fields in rp
eosc-kc/keycloak-community pull request #2
Opened 2020-12-23 07:52 UTC by cgeorgilakis

2021-01-08 09:42 UTC, NicolasLiampotis requested changes
Minor edits and questions

2021-01-08 09:42 UTC, NicolasLiampotis commented on design/oidc_federation.md
> +- `trust_anchor_ids` (required): List containing the entity identifier of the trust anchors.
"... containing the entity identifiers of the ..."

2021-01-08 09:42 UTC, NicolasLiampotis commented on design/oidc_federation.md
> +We propose to use authorization request in automatic registration which is already supported by Keycloak. Keycloak will try to interact with the Federated OP without going through a registration proc
Replace with
"Automatic registration will allow Keycloak to act as an RP that can send authorization requests to an OP without first registering with the OP. We propose to perform the request by passing a request object by value as described in section 6.1 in OpenID Connect Core 1.0, which is already supported by Keycloak.

2021-01-08 09:42 UTC, NicolasLiampotis commented on design/oidc_federation.md
> +To support this, the request parameter should contain the signed entity statement of Federation OIDC Identity Provider saved on Keycloak. Entity Statement value is same as described in [Well-known OI
I don't understand this. According to https://openid.net/specs/openid-connect-federation-1_0.html#rfc.section.9.1.1.1, the request parameter value "is a JWT whose Claims are the request parameters specified in Section 3.1.2 in OpenID Connect Core 1.0. The JWT MUST be signed and MAY be encrypted." Is this the same as the "signed entity statement of Federation OIDC Identity Provider"?

2021-01-08 09:42 UTC, NicolasLiampotis commented on design/oidc_federation.md
> +This .well-known is mandatory for a successful automatic registration process. Response content type MUST be set to application/jose.RP Metadata need to be constructed from the defined Federation OID
"This .well-known endpoint is mandatory..."

2021-01-08 09:42 UTC, NicolasLiampotis commented on design/oidc_federation.md
> +The relative path could follow the format: http(s)://host:port/{basepath}/realms/{realm-name}/{rp_alias}/.well-known/openid-federation - http(s)://host:port/{basepath}/realms/{realm-name}/{rp_alias}
is this rp_alias or idp_alias? in the previous line we mention "the alias name of the idp prepended"

2021-01-08 13:42 UTC, cgeorgilakis commented on design/oidc_federation.md
> +To support this, the request parameter should contain the signed entity statement of Federation OIDC Identity Provider saved on Keycloak. Entity Statement value is same as described in [Well-known OI
You are right. I have changed this part.

2021-01-08 13:43 UTC, cgeorgilakis commented on design/oidc_federation.md
> +The relative path could follow the format: http(s)://host:port/{basepath}/realms/{realm-name}/{rp_alias}/.well-known/openid-federation - http(s)://host:port/{basepath}/realms/{realm-name}/{rp_alias}
idp_alias. I have confused with terminology because we are talking about implemmenting RP part. I will change it.

2021-01-08 13:43 UTC, cgeorgilakis commented
I have implemented requested changes

2021-01-11 12:46 UTC, NicolasLiampotis approved these changes
LGTM

2021-01-11 12:47 UTC, merged